
title: Guven Ozgur
url: 'http://guvenozgur.com'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Guven Ozgur
tagline: Computer Engineer
pic: profil.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hguvenozgur@gmail.com
phone: 0505579****
website: guvenozgur.com #do not add http://
linkedin: 
github: guvenozgur
twitter: '@gwenozgur'

#Update all the sections by editing the files inside _includes folder.
